services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    platform: linux/arm64
    environment:
      - OPENAI_API_KEY=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
      - USER=namastex
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"

volumes:
  mem0_storage:
