services:
  automagik:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        AUTOMAGIK_API_PORT: ${AUTOMAGIK_API_PORT:-8881}
    image: automagik:latest
    container_name: automagik
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../.env
    environment:
      # Keep all your existing environment variables
      - AUTOMAGIK_API_KEY=${AUTOMAGIK_API_KEY}
      - AUTOMAGIK_API_HOST=0.0.0.0
      - AUTOMAGIK_API_PORT=${AUTOMAGIK_API_PORT:-8881}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - AUTOMAGIK_LOG_LEVEL=${AUTOMAGIK_LOG_LEVEL:-INFO}
      - AUTOMAGIK_TIMEZONE=${AUTOMAGIK_TIMEZONE:-UTC}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-openai:gpt-4.1-mini}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      
      # Override database URL for Docker - automatically extract credentials from DATABASE_URL if needed
      - AUTOMAGIK_DATABASE_URL=postgresql://automagik_user:automagik_pass@localhost:${POSTGRES_PORT:-5432}/automagik_db
      - AUTOMAGIK_POSTGRES_POOL_MIN=${AUTOMAGIK_POSTGRES_POOL_MIN:-10}
      - AUTOMAGIK_POSTGRES_POOL_MAX=${AUTOMAGIK_POSTGRES_POOL_MAX:-25}
    depends_on:
      automagik-db:
        condition: service_healthy
    volumes:
      - ../automagik:/app/automagik
      # Mount Claude CLI credentials from host (create if missing)
      - ~/.claude:/root/.claude:ro
      # Mount MCP configuration from project root
      - ../.mcp.json:/app/.mcp.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AUTOMAGIK_API_PORT:-8881}/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  automagik-db:
    image: postgres:15
    container_name: automagik-db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: automagik_db
      POSTGRES_USER: automagik_user
      POSTGRES_PASSWORD: automagik_pass
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: ${POSTGRES_PORT:-5432}
    volumes:
      - automagik_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automagik_user -d automagik_db -p ${POSTGRES_PORT:-5432}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  automagik_postgres_data: