services:
  automagik-agents-dev:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        AUTOMAGIK_AGENTS_API_PORT: ${AUTOMAGIK_AGENTS_API_PORT:-8881}
    image: automagik-agents:latest
    container_name: automagik-agents-dev
    env_file:
      - ../.env
    ports:
      - "${AUTOMAGIK_AGENTS_API_PORT:-8881}:${AUTOMAGIK_AGENTS_API_PORT:-8881}"
    environment:
      # Keep all your existing environment variables
      - AM_API_KEY=${AM_API_KEY}
      - AUTOMAGIK_AGENTS_API_HOST=0.0.0.0
      - AUTOMAGIK_AGENTS_API_PORT=${AUTOMAGIK_AGENTS_API_PORT:-8881}
      - AUTOMAGIK_AGENTS_ENV=${AUTOMAGIK_AGENTS_ENV:-development}
      - AUTOMAGIK_AGENTS_LOG_LEVEL=${AUTOMAGIK_AGENTS_LOG_LEVEL:-INFO}
      - AUTOMAGIK_TIMEZONE=${AUTOMAGIK_TIMEZONE:-UTC}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-openai:gpt-4.1-mini}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      
      # Override ONLY the host-related variables for Docker
      - AUTOMAGIK_AGENTS_POSTGRES_HOST=automagik-agents-db
      - AUTOMAGIK_AGENTS_POSTGRES_PORT=5432
      - AUTOMAGIK_AGENTS_POSTGRES_USER=${AUTOMAGIK_AGENTS_POSTGRES_USER:-postgres}
      - AUTOMAGIK_AGENTS_POSTGRES_PASSWORD=${AUTOMAGIK_AGENTS_POSTGRES_PASSWORD:-postgres}
      - AUTOMAGIK_AGENTS_POSTGRES_DB=${AUTOMAGIK_AGENTS_POSTGRES_DB:-automagik}
      - AUTOMAGIK_AGENTS_DATABASE_URL=postgresql://${AUTOMAGIK_AGENTS_POSTGRES_USER:-postgres}:${AUTOMAGIK_AGENTS_POSTGRES_PASSWORD:-postgres}@automagik-agents-db:5432/${AUTOMAGIK_AGENTS_POSTGRES_DB:-automagik}
    depends_on:
      automagik-agents-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ../src:/app/src
    networks:
      - automagik_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AUTOMAGIK_AGENTS_API_PORT:-8881}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  automagik-agents-db:
    image: postgres:15
    container_name: automagik-agents-db
    environment:
      POSTGRES_DB: ${AUTOMAGIK_AGENTS_POSTGRES_DB:-automagik}
      POSTGRES_USER: ${AUTOMAGIK_AGENTS_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTOMAGIK_AGENTS_POSTGRES_PASSWORD:-postgres}
    ports:
      - "${AUTOMAGIK_AGENTS_POSTGRES_PORT:-5432}:5432"
    volumes:
      - automagik_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - automagik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTOMAGIK_AGENTS_POSTGRES_USER:-postgres} -d ${AUTOMAGIK_AGENTS_POSTGRES_DB:-automagik}"]}]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  automagik_postgres_data:

networks:
  automagik_network:
    driver: bridge