services:
  automagik-agents-dev:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        AM_PORT: ${AM_PORT:-8881}
    image: automagik-agents:latest
    container_name: automagik-agents-dev
    env_file:
      - ../.env
    ports:
      - "${AM_PORT:-8881}:${AM_PORT:-8881}"
    environment:
      # Keep all your existing environment variables
      - AM_API_KEY=${AM_API_KEY}
      - AM_HOST=0.0.0.0
      - AM_PORT=${AM_PORT:-8881}
      - AM_ENV=${AM_ENV:-development}
      - AM_LOG_LEVEL=${AM_LOG_LEVEL:-INFO}
      - AM_TIMEZONE=${AM_TIMEZONE:-UTC}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-openai:gpt-4.1-mini}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      
      # Override ONLY the host-related variables for Docker
      - POSTGRES_HOST=automagik-agents-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-automagik}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@automagik-agents-db:5432/${POSTGRES_DB:-automagik}
    depends_on:
      automagik-agents-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ../src:/app/src
    networks:
      - automagik_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AM_PORT:-8881}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  automagik-agents-db:
    image: postgres:15
    container_name: automagik-agents-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-automagik}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - automagik_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - automagik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-automagik}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  automagik_postgres_data:

networks:
  automagik_network:
    driver: bridge