services:
  automagik-agents-prod:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: automagik-agents:latest
    container_name: automagik-agents-prod
    env_file:
      - ../.env.prod
    ports:
      - "${AUTOMAGIK_AGENTS_API_PORT:-18881}:${AUTOMAGIK_AGENTS_API_PORT:-18881}"
    environment:
      - AM_API_KEY=${AM_API_KEY}
      - AUTOMAGIK_AGENTS_API_HOST=${AUTOMAGIK_AGENTS_API_HOST}
      - AUTOMAGIK_AGENTS_API_PORT=${AUTOMAGIK_AGENTS_API_PORT:-18881}
      - AUTOMAGIK_AGENTS_ENV=${AUTOMAGIK_AGENTS_ENV:-production}
      - AUTOMAGIK_AGENTS_LOG_LEVEL=${AUTOMAGIK_AGENTS_LOG_LEVEL:-DEBUG}
      - AUTOMAGIK_TIMEZONE=${AUTOMAGIK_TIMEZONE:-UTC}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-openai:gpt-4.1-mini}
      - AUTOMAGIK_AGENTS_DATABASE_URL=${AUTOMAGIK_AGENTS_DATABASE_URL}
      - AUTOMAGIK_AGENTS_POSTGRES_HOST=${AUTOMAGIK_AGENTS_POSTGRES_HOST}
      - AUTOMAGIK_AGENTS_POSTGRES_PORT=${AUTOMAGIK_AGENTS_POSTGRES_PORT}
      - AUTOMAGIK_AGENTS_POSTGRES_USER=${AUTOMAGIK_AGENTS_POSTGRES_USER}
      - AUTOMAGIK_AGENTS_POSTGRES_PASSWORD=${AUTOMAGIK_AGENTS_POSTGRES_PASSWORD}
      - AUTOMAGIK_AGENTS_POSTGRES_DB=${AUTOMAGIK_AGENTS_POSTGRES_DB}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - ../src:/app/src
    networks:
      - automagik_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AUTOMAGIK_AGENTS_API_PORT:-18881}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


volumes:
  automagik_postgres_data:

networks:
  automagik_network:
    driver: bridge
