version: '3.8'

services:
  claude-code-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-dev
    volumes:
      # Workspace volume for persistence
      - claude-workspace:/workspace
      # Docker socket for docker-in-docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Workflow configuration
      - ../workflows/bug-fixer:/workspace/workflow:ro
      # SSH keys for git operations
      - ~/.ssh:/home/claude/.ssh:ro
    environment:
      - GIT_BRANCH=NMSTX-187-langgraph-orchestrator-migration
      - WORKSPACE_DIR=/workspace/am-agents-labs
      - WORKFLOW_DIR=/workspace/workflow
    networks:
      - claude-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Security context
    security_opt:
      - no-new-privileges:true
    # Health check
    healthcheck:
      test: ["CMD", "claude", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Override default command for interactive development
    command: ["echo", "Claude Code Agent Development Container Ready"]
    stdin_open: true
    tty: true

volumes:
  claude-workspace:
    driver: local
    name: claude-code-workspace

networks:
  claude-network:
    driver: bridge
    name: claude-code-network