name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run linting
      run: |
        ruff check automagik tests
        ruff format --check automagik tests
    
    - name: Run unit tests
      run: |
        pytest tests/agents/simple/test_simple_agent.py \
               tests/agents/sofia/test_sofia_agent.py \
               tests/agents/claude_code/test_agent.py \
               tests/agents/claude_code/test_models.py \
               tests/api/test_agent_routes.py \
               tests/api/test_system_endpoints.py \
               -v --cov=automagik --cov-report=xml --cov-report=term
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DATABASE_URL: sqlite:///test.db
    
    - name: Run integration tests
      run: |
        pytest tests/integration/test_agent_parity.py \
               tests/agents/claude_code/test_integration.py \
               -v -m "not slow"
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DATABASE_URL: sqlite:///test.db
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false